learning_rate: 0.002
lr_scheduler: StepLR
lr_step_size: 125
lr_gamma: 0.5
epochs: 500
batch_size: 128

en1_units: 300
dropout: 0.3

pos_threshold: 0.4

temperature: 0.2  # Already exists
tau: 1.0  # Add this parameter